WEB_SERVER_HOST = "WEB_SERVER_HOST"
WEB_SERVER_PORT = "WEB_SERVER_PORT"

SERVER_SUPPORTED_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"]
PAYLOAD_REQUIRED_METHODS = SERVER_SUPPORTED_METHODS[0:] # Ignore 'GET'

